---
# tasks file for cask

  - name: Update Homebrew
    homebrew:
      update_homebrew=yes

  - name: Install Brew Caskroom
    homebrew:
      name=cask
      state=present

  - name: Change the cask directory to /Applications
    lineinfile:
      dest=~/.profile
      insertafter=EOF
      state=present
      line="export HOMEBREW_CASK_OPTS="--appdir=/Applications""

  - name: Add the Casks
    homebrew_cask:
      name={{ item }}
      state=present
    with_items:
      - chrome-devtools
      - cord
      - github-desktop
      - google-chrome
      - gpgtools
      - handbrake
      - istat-menus
      - istumbler
      - iterm2
      - java
      - macdown
      - mactex
      - macvim
      - mysqlworkbench
      - pgadmin4
      - sublime-text
      - terraform
      - textwrangler
      - tower
      - transmit
      - transmission
      - tunnelblick
      - virtualbox
      - vagrant
      - vagrant-manager
      - virtualbox
